Repository deepreview-dave/app, pull requests merged in 2022-12, with the labels that each got.

#1 functional components + zustand
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/state/state.ts
Labels: enhancement

#2 changed UI a bit
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/index.tsx
  src/state/state.ts
Labels: enhancement, help wanted

#3 Fixed the bug with loading states not blocking the whole UI
  src/App.tsx
Labels: enhancement

#4 Factor out editor controls from app
  src/App.tsx
  src/components/NameEditor.tsx
  src/components/PerformanceScoreEditor.tsx
Labels: enhancement

#5 Add support for Prettier code formatter
  .prettierignore
  .prettierrc.json
  README.md
  functions/smarts.ts
  functions/tsconfig.json
  package-lock.json
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Footer.tsx
  src/components/NameEditor.tsx
  src/components/Navbar.tsx
  src/components/PerformanceScoreEditor.tsx
  src/index.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  src/smarts.ts
  src/state/state.ts
  tsconfig.json
Labels: documentation, enhancement

#11 fix footer
  src/App.tsx
Labels: bug

#10 small fix on selector
  src/components/PerformanceScoreEditor.tsx
Labels: bug

#7 added loading spinner
  src/App.tsx
  src/components/ResultBlock.tsx
Labels: enhancement

#18 added skeleton for even more options
  src/App.css
  src/App.tsx
  src/business/utils.ts
  src/components/MoreAttributes.tsx
  src/components/ReviewHeader.tsx
  src/state/defaults.ts
  src/state/state.ts
Labels: enhancement, good first issue, question

#23 Fixed resetting the perf score
  src/components/PerformanceScoreEditor.tsx
Labels: bug

#24 moved modal state to different zustand file
  src/components/DepartmentEditor.tsx
  src/components/MoreAttributes.tsx
  src/components/NameEditor.tsx
  src/components/PerformanceScoreEditor.tsx
  src/components/ResultBlock.tsx
  src/components/ReviewHeader.tsx
  src/components/RoleEditor.tsx
  src/components/SubmitControl.tsx
  src/state/app.state.ts
  src/state/defaults.ts
  src/state/modal.state.ts
Labels: enhancement

#26 Feat/add attributes to prompt
  functions/auto-generate-perf-review.ts
  src/business/auto-perf-review-generator.ts
  src/business/common.ts
  src/business/prompt-builder.ts
  src/components/MoreAttributes.tsx
  src/components/PerformanceScoreEditor.tsx
  src/components/SubmitControl.tsx
  src/state/app.state.ts
Labels: enhancement

#40 fixed copy for attributes
  src/components/MoreAttributes.tsx
  src/state/defaults.ts
Labels: enhancement

#42 Feat/optional period selector
  functions/auto-generate-perf-review.ts
  src/App.tsx
  src/business/common.ts
  src/business/prompt-builder.ts
  src/components/SubmitControl.tsx
  src/components/TimePeriodEditor.tsx
  src/state/app.state.ts
  src/state/defaults.ts
Labels: enhancement

#45 rename trait to strength
  src/business/common.ts
  src/business/prompt-builder.ts
  src/components/MoreAttributes.tsx
  src/state/defaults.ts
Labels: enhancement

#47 Added more copy
  src/components/MoreAttributes.tsx
Labels: enhancement

#48 trying with a logo
  public/favicon.ico
  src/App.css
  src/components/Navbar.tsx
  src/components/logo.svg
Labels: enhancement

#56 cleaned up copy & look
  public/index.html
  src/App.css
  src/App.tsx
  src/components/DepartmentEditor.tsx
  src/components/MoreAttributes.tsx
  src/components/NameEditor.tsx
  src/components/Navbar.tsx
  src/components/PageInfo.tsx
  src/components/PerformanceScoreEditor.tsx
  src/components/ResultBlock.tsx
  src/components/RoleEditor.tsx
  src/components/TimePeriodEditor.tsx
Labels: enhancement

#60 add pronoun enditor
  functions/auto-generate-perf-review.ts
  src/App.tsx
  src/business/common.ts
  src/business/prompt-builder.ts
  src/components/PronounEditor.tsx
  src/components/SubmitControl.tsx
  src/state/app.state.ts
Labels: enhancement

#61 allow editing
  src/components/ResultBlock.module.sass
  src/components/ResultBlock.tsx
  src/components/SubmitControl.tsx
  src/components/copy-to-clipboard.svg
  src/state/app.state.ts
Labels: enhancement

#57 analytics w/o key
  .env
  package-lock.json
  package.json
  src/business/analytics.ts
  src/components/ResultBlock.tsx
  src/index.tsx
  src/state/app.state.ts
Labels: enhancement

#66 save state
  src/components/ResultBlock.tsx
  src/state/app.state.ts
Labels: enhancement

#67 better text
  src/business/prompt-builder.ts
  src/state/app.state.ts
Labels: enhancement
